#!/bin/sh
mvn package

# Remove timestamps from documentation
unamestr=`uname`
if [[ "$unamestr" == "Linux" ]]
then
  find docs -type f -name "*.html" -exec sed -i -E "/<!-- Generated by groovydoc .* -->/d" {} ';'
  find docs -type f -name "*.html" -exec sed -i -E "/<meta name=\"date\" content=/d" {} ';'
else
  find docs -type f -name "*.html" -exec ex -sc "g/<!-- Generated by groovydoc .* -->/d" -cx {} ';'
  find docs -type f -name "*.html" -exec ex -sc "g/<meta name=\"date\" content=/d" -cx {} ';'
fi