#!/bin/sh
mvn package
find docs -type f -name "*.html" -exec ex -sc "g/<!-- Generated by groovydoc .* -->/d" -cx {} ';'
find docs -type f -name "*.html" -exec ex -sc "g/<meta name=\"date\" content=/d" -cx {} ';'
