FROM alpine

RUN apk add git maven openjdk8 bash zip curl -f

COPY ./src            /usr/src/src
COPY ./test           /usr/src/test
COPY ./pom.xml        /usr/src/pom.xml
COPY ./test.sh        /usr/src/test.sh

WORKDIR /usr/src/

ENTRYPOINT ["/usr/src/test.sh"]
